CashMachine/CashMachineWeb/Models/WithdrawViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CashMachineWeb.Models
{
	public class WithdrawViewModel
	{
		[Required]
		public decimal WithdrawAmount { get; set; }
	}
}

CashMachine/CashMachineWeb/Controllers/OperationsController.cs
using System;
using System.Web.Mvc;
using CashMachineWeb.Database;
using CashMachineWeb.Domain;
using CashMachineWeb.Models;

namespace CashMachineWeb.Controllers
{
	[Authorize]
	public class OperationsController : Controller
	{
		private readonly IAccountOperationsService operationsService;

		public OperationsController(IAccountOperationsService operationsService)
		{
			this.operationsService = operationsService;
		}

		// Bastard-Injection DI anti-pattern! Never do it in real systems, used here just for simplicity and testability
		// asume it is not there for design and usage purposes
		public OperationsController() : this(new AccountOperationsService(new CashMachineDbContext()))
		{
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Balance()
		{
			var balanceModel = operationsService.GetBalanceForAccount(AccountNumber);
			return View(balanceModel);
		}

		public ActionResult Withdraw()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Withdraw(WithdrawViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				try
				{
					OperationResult operationResult = operationsService.WithdrawMoney(AccountNumber, viewModel.WithdrawAmount);
					TempData["OperationResult"] = operationResult;
					return RedirectToAction("OperationReport");
				}
				catch (AmountExceededException exception)
				{
					// ideally we do some logging than display message to a user
					TempData["ErrorMessage"] =
						"Your request could not be proceed. You've exceeded your account limit on that operation request";
					return RedirectToAction("Index", "Error");
				}

			}

			// If we got this far, validation failed, redisplay form
			return View(viewModel);
		}

		public ActionResult OperationReport()
		{
			var operationResult = TempData["OperationResult"] as OperationResult;
			return View(operationResult);
		}

		private string AccountNumber
		{
			get { return User.Identity.Name; }
		}
	}
}

CashMachine/CashMachineWeb/Views/Operations/Balance.cshtml
@model CashMachineWeb.Domain.AccountBalanceStamp

@{
	ViewBag.Title = "Balance";
}

<h2>Balance</h2>
<hr />

<div class="panel">
	@Html.DisplayForModel()

	<div>
		@Html.ActionLink("Back", "Index", "Operations", null, new { @class = "btn btn-default" })
	</div>
</div>

CashMachine/CashMachineWeb/Views/Operations/Index.cshtml
@model dynamic

@{
	ViewBag.Title = "Credit Card Operations";
}

<h2>Please select operation you need</h2>
<ul class="list-group">
	<li class="list-group-item">@Html.ActionLink("Account balance", "Balance", "Operations")</li>
	<li class="list-group-item">@Html.ActionLink("Withdraw money", "Withdraw", "Operations")</li>
</ul>

CashMachine/CashMachineWeb/Views/Operations/OperationReport.cshtml
@model CashMachineWeb.Domain.OperationResult

@{
	ViewBag.Title = "Operation Report";
}

<h2>Operation Report</h2>
<hr />

<div class="panel">
	@Html.DisplayForModel()

	<div>
		@Html.ActionLink("Back", "Index", "Operations", null, new { @class = "btn btn-default" })
	</div>
</div>

CashMachine/CashMachineWeb/Views/Operations/Withdraw.cshtml
@model  CashMachineWeb.Models.WithdrawViewModel

@{
	ViewBag.Title = "Withdraw money";
}

<h2>Withdraw money from account</h2>

@using (Html.BeginForm("Withdraw", "Operations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
	@Html.AntiForgeryToken()
	<hr/>
	@Html.ValidationSummary()

	<div class="form-group">
		<div class="col-md-10">
			@Html.TextBoxFor(m => m.WithdrawAmount, new { @id = "withdrawAmountInput", @class = "form-control", @readonly = "" })
		</div>
	</div>

	@Html.Partial("_NumericKeyboard")
}